import {
  generateName,
  generateLat,
  generateLng,
  generateState,
} from "./generator/randomGenerator";

export const hospitals: Hospital[] = [
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
  {
    name: generateName(),
    lat: generateLat(),
    lng: generateLng(),
    stateIcuLow: generateState(),
    stateIcuHigh: generateState(),
    stateEcmo: generateState(),
  },
];
